apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservicio-deployment
  labels:
    app: microservicio
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: microservicio
    template:
      labels:
        app: microservicio
    spec:
      containers:
      - name: microservicio 
        image: arielquispe/microservicio:latest
        ports:
        - containerPort: 8085
